### ISSUE TITLE
Support adding custom resource.Detectors / resource.Options

### ISSUE THREAD

**Issue by dstrelau** [honeycombio/otel-config-go#12]
I'd like to be able to add custom Detectors, like the ones [in sdk/resource](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/resource#Option) or the [ones in contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/detectors) for cloud providers.

There are two problems here:

1) I _think_ the fix is something like adding `func WithResourceOptions(...resource.Option) Option` and then passing those to the `resource.New` call [here](https://github.com/honeycombio/otel-launcher-go/blob/main/launcher/launcher.go#L409-L413) (and `sdk/resource.WithDetectors` returns a `resource.Option` so that covers the contrib Detectors too). However, the error returned from `resource.New` is ignored right now and I know at least some of the AWS Detectors will return errors when not on an appropriate platform (eg, the EKS detector returns and error when not running on EKS). I'm not sure if it's worth threading that error all the way back up to the caller of `ConfigureOpenTelemetry` or if there are other options I'm not seeing. I'd like some advice before attempting a fix.

2) The `semconv` versions imported in this project ([v1.10.0](https://github.com/honeycombio/otel-launcher-go/blob/main/launcher/launcher.go#L22)) and in those other libraries ([v1.17.0](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/detectors/aws/ec2/ec2.go#L28)) are different, meaning that the `semconv.SchemaURL` values are different, meaning that any attempt to merge them together will fail. Happy to submit a PR to upgrade this package's version if that sounds like a reasonable fix.

**Comment by MikeGoldsmith** [comment]
Hey @dstrelau - sorry for the delay in responding.

I don't see a reason why we can't upgrade to semconv v1.17 to match the other deps. Please do submit a PR to fix 👍 

Regarding the supporting additional Resource Detectors, I think your idea of extending the API to include something like `WithResourceOptions` makes sense. Any error configuring the SDK should bubble up to the `ConfigureOpenTelemetry` call so the user has the option of failing or logging. We'd be happy for you to have a go at extending the API, alternatively, we'll add this to our backlog to extend when we next schedule some maintenance on the launcher.

**Comment by MikeGoldsmith** [comment]
Created this ticket to update semconv separatley:
- https://github.com/honeycombio/otel-launcher-go/issues/18
