### ISSUE TITLE
Environment takes precedence over otelconfig.WithServiceName

### ISSUE THREAD

**Issue by stfp** [honeycombio/otel-config-go#124]
The `OTEL_SERVICE_NAME` environment variable takes precedence over values set with `otelconfig.WithServiceName`.

This is similar to https://github.com/honeycombio/otel-config-go/issues/120 (which was fixed in https://github.com/honeycombio/otel-config-go/pull/123, thank you!) but with `ServiceName`

**Versions**

Unreleased head of `main` branch with https://github.com/honeycombio/otel-config-go/pull/123 merged

**Steps to reproduce**

The following test should pass, but it fails with `error: unexpected service name: name_from_env`

```go
func TestServiceNamePrecedence(t *testing.T) {
	nameFromEnv, nameFromCode := "name_from_env", "name_from_code"

	// we'll use ValidateConfig to check whe service name
	expectedName := nameFromCode
	otelconfig.ValidateConfig = func(config *otelconfig.Config) error {
		if config.ServiceName != expectedName {
			return fmt.Errorf("unexpected service name: %s", config.ServiceName)
		}
		return nil
	}

	// set service name from env
	os.Setenv("OTEL_SERVICE_NAME", nameFromEnv)

	shutdown, err := otelconfig.ConfigureOpenTelemetry(
		otelconfig.WithServiceName(nameFromCode),
		otelconfig.WithTracesEnabled(false),
		otelconfig.WithMetricsEnabled(false))
	if err != nil {
		t.Fatalf("error: %v", err)
		return
	}
	shutdown()
}
```

**Comment by MikeGoldsmith** [comment]
Hi @stfp - thanks for opening the issue.

We've intentionally made env var take precedence over code configuration to maximise the operator influence of running code without requiring code changes.

Is there a specific use-case where you would want code configuration to have precedence over env vars?

**Comment by stfp** [comment]
Hmm, nope, you're right. I saw some broken tests on my end, but as it turns out the new behavior will let us remove a workaround we had against the old precedence. Tests were only there to make sure we'd notice this kind of change. 

Sorry about the noise!
